// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Autogenerate sidebars for each documentation section
  guidesSidebar: [{type: 'autogenerated', dirName: 'guides'}],
  documentationSidebar: [{type: 'autogenerated', dirName: 'documentation'}],
};

module.exports = sidebars;
